version: '3'
services:
  postgres-test:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: testdb
    volumes:
      - postgres-test-data:/var/lib/postgresql/data

volumes:
  postgres-test-data: 